# permissions for end users to view spacetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: spacetemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kube-multitenancy-space-controller
    app.kubernetes.io/part-of: kube-multitenancy-space-controller
    app.kubernetes.io/managed-by: kustomize
  name: spacetemplate-viewer-role
rules:
- apiGroups:
  - github.sanjivmadhavan.io
  resources:
  - spacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - github.sanjivmadhavan.io
  resources:
  - spacetemplates/status
  verbs:
  - get
