apiVersion: github.sanjivmadhavan.io/v1alpha1
kind: Space
metadata:
  labels:
    app.kubernetes.io/name: space
    app.kubernetes.io/instance: space-sample
    app.kubernetes.io/part-of: kube-multitenancy-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-multitenancy-operator
  name: space-sample-add-rb
spec:
  additionalRoleBindings:
    - roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: viewer
      subjects:
        - name: Sam
          kind: User