apiVersion: github.sanjivmadhavan.io/v1alpha1
kind: Space
metadata:
  labels:
    app.kubernetes.io/name: space
    app.kubernetes.io/instance: space-sample
    app.kubernetes.io/part-of: kube-multitenancy-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kube-multitenancy-operator
  name: space-sample-sa-aws
spec:
  serviceAccounts:
    items:
      - name: rds
        annotations:
          eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/rds

