apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-multitenancy-space-controller.fullname" . }}-controller-manager-metrics-service
  labels:
    {{- include "kube-multitenancy-space-controller.labels" . | nindent 4 }}
  {{- with .Values.customAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    {{- include "kube-multitenancy-space-controller.selectorLabels" . | nindent 4 }}
